spring:
  application:
    name: "U6P1"

  data:
    mongodb:
      uri: mongodb://localhost:27017/practica_db

security:
  jwt:
    key:
      private: ElbkyHuoM9F9KyxXvwheCajA8VmcVFXCRDc7uj6dNP4

springdoc:
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
    default-models-expand-depth: -1
    operations-sorter: method
    tags-sorter: alpha
    filter: true
  api-docs:
    enabled: true
    path: /v3/doc

# Server config
server:
  port: 8081